//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_es {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_es() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Core.Resource.es", typeof(Resource_es).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string CreateAccessPin {
            get {
                return ResourceManager.GetString("CreateAccessPin", resourceCulture);
            }
        }
        
        internal static string PinCreatedSuccess {
            get {
                return ResourceManager.GetString("PinCreatedSuccess", resourceCulture);
            }
        }
        
        internal static string ForgotPin {
            get {
                return ResourceManager.GetString("ForgotPin", resourceCulture);
            }
        }
        
        internal static string ConfirmPin {
            get {
                return ResourceManager.GetString("ConfirmPin", resourceCulture);
            }
        }
        
        internal static string EnterPin {
            get {
                return ResourceManager.GetString("EnterPin", resourceCulture);
            }
        }
        
        internal static string DiferentPin {
            get {
                return ResourceManager.GetString("DiferentPin", resourceCulture);
            }
        }
        
        internal static string InvalidPin {
            get {
                return ResourceManager.GetString("InvalidPin", resourceCulture);
            }
        }
        
        internal static string OnboardingWelcome {
            get {
                return ResourceManager.GetString("OnboardingWelcome", resourceCulture);
            }
        }
        
        internal static string OnboardingDescription {
            get {
                return ResourceManager.GetString("OnboardingDescription", resourceCulture);
            }
        }
        
        internal static string OnboardingCall {
            get {
                return ResourceManager.GetString("OnboardingCall", resourceCulture);
            }
        }
        
        internal static string OnboardingEmail {
            get {
                return ResourceManager.GetString("OnboardingEmail", resourceCulture);
            }
        }
        
        internal static string OnboardingChat {
            get {
                return ResourceManager.GetString("OnboardingChat", resourceCulture);
            }
        }
        
        internal static string OnboardingFile {
            get {
                return ResourceManager.GetString("OnboardingFile", resourceCulture);
            }
        }
        
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        internal static string Telephone {
            get {
                return ResourceManager.GetString("Telephone", resourceCulture);
            }
        }
        
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        internal static string NeedHelp {
            get {
                return ResourceManager.GetString("NeedHelp", resourceCulture);
            }
        }
        
        internal static string EmailInvalid {
            get {
                return ResourceManager.GetString("EmailInvalid", resourceCulture);
            }
        }
        
        internal static string EmailPasswordEmpty {
            get {
                return ResourceManager.GetString("EmailPasswordEmpty", resourceCulture);
            }
        }
        
        internal static string ManageContacts {
            get {
                return ResourceManager.GetString("ManageContacts", resourceCulture);
            }
        }
        
        internal static string Invites {
            get {
                return ResourceManager.GetString("Invites", resourceCulture);
            }
        }
        
        internal static string MyAccount {
            get {
                return ResourceManager.GetString("MyAccount", resourceCulture);
            }
        }
        
        internal static string Config {
            get {
                return ResourceManager.GetString("Config", resourceCulture);
            }
        }
        
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        internal static string RegisterFingerprint {
            get {
                return ResourceManager.GetString("RegisterFingerprint", resourceCulture);
            }
        }
        
        internal static string TouchSensor {
            get {
                return ResourceManager.GetString("TouchSensor", resourceCulture);
            }
        }
        
        internal static string NeedsEmailConfirmation {
            get {
                return ResourceManager.GetString("NeedsEmailConfirmation", resourceCulture);
            }
        }
        
        internal static string LicenceExpired {
            get {
                return ResourceManager.GetString("LicenceExpired", resourceCulture);
            }
        }
        
        internal static string UserBlocked {
            get {
                return ResourceManager.GetString("UserBlocked", resourceCulture);
            }
        }
        
        internal static string NeedsConfirmUserChange {
            get {
                return ResourceManager.GetString("NeedsConfirmUserChange", resourceCulture);
            }
        }
        
        internal static string NoInternt {
            get {
                return ResourceManager.GetString("NoInternt", resourceCulture);
            }
        }
        
        internal static string ErrorDeviceRegister {
            get {
                return ResourceManager.GetString("ErrorDeviceRegister", resourceCulture);
            }
        }
        
        internal static string PleaseContactUs {
            get {
                return ResourceManager.GetString("PleaseContactUs", resourceCulture);
            }
        }
        
        internal static string UsedOf {
            get {
                return ResourceManager.GetString("UsedOf", resourceCulture);
            }
        }
        
        internal static string LogoutQuestion {
            get {
                return ResourceManager.GetString("LogoutQuestion", resourceCulture);
            }
        }
        
        internal static string LogoutQuestionChatHistory {
            get {
                return ResourceManager.GetString("LogoutQuestionChatHistory", resourceCulture);
            }
        }
    }
}
