//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Core.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string CreateAccessPin {
            get {
                return ResourceManager.GetString("CreateAccessPin", resourceCulture);
            }
        }
        
        public static string PinCreatedSuccess {
            get {
                return ResourceManager.GetString("PinCreatedSuccess", resourceCulture);
            }
        }
        
        public static string ForgotPin {
            get {
                return ResourceManager.GetString("ForgotPin", resourceCulture);
            }
        }
        
        public static string ConfirmPin {
            get {
                return ResourceManager.GetString("ConfirmPin", resourceCulture);
            }
        }
        
        public static string EnterPin {
            get {
                return ResourceManager.GetString("EnterPin", resourceCulture);
            }
        }
        
        public static string DiferentPin {
            get {
                return ResourceManager.GetString("DiferentPin", resourceCulture);
            }
        }
        
        public static string InvalidPin {
            get {
                return ResourceManager.GetString("InvalidPin", resourceCulture);
            }
        }
        
        public static string OnboardingWelcome {
            get {
                return ResourceManager.GetString("OnboardingWelcome", resourceCulture);
            }
        }
        
        public static string OnboardingDescription {
            get {
                return ResourceManager.GetString("OnboardingDescription", resourceCulture);
            }
        }
        
        public static string OnboardingCall {
            get {
                return ResourceManager.GetString("OnboardingCall", resourceCulture);
            }
        }
        
        public static string OnboardingEmail {
            get {
                return ResourceManager.GetString("OnboardingEmail", resourceCulture);
            }
        }
        
        public static string OnboardingChat {
            get {
                return ResourceManager.GetString("OnboardingChat", resourceCulture);
            }
        }
        
        public static string OnboardingFile {
            get {
                return ResourceManager.GetString("OnboardingFile", resourceCulture);
            }
        }
        
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        public static string Telephone {
            get {
                return ResourceManager.GetString("Telephone", resourceCulture);
            }
        }
        
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        public static string NeedHelp {
            get {
                return ResourceManager.GetString("NeedHelp", resourceCulture);
            }
        }
        
        public static string EmailInvalid {
            get {
                return ResourceManager.GetString("EmailInvalid", resourceCulture);
            }
        }
        
        public static string EmailPasswordEmpty {
            get {
                return ResourceManager.GetString("EmailPasswordEmpty", resourceCulture);
            }
        }
        
        public static string ManageContacts {
            get {
                return ResourceManager.GetString("ManageContacts", resourceCulture);
            }
        }
        
        public static string Invites {
            get {
                return ResourceManager.GetString("Invites", resourceCulture);
            }
        }
        
        public static string MyAccount {
            get {
                return ResourceManager.GetString("MyAccount", resourceCulture);
            }
        }
        
        public static string Config {
            get {
                return ResourceManager.GetString("Config", resourceCulture);
            }
        }
        
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        public static string RegisterFingerprint {
            get {
                return ResourceManager.GetString("RegisterFingerprint", resourceCulture);
            }
        }
        
        public static string TouchSensor {
            get {
                return ResourceManager.GetString("TouchSensor", resourceCulture);
            }
        }
        
        public static string NeedsEmailConfirmation {
            get {
                return ResourceManager.GetString("NeedsEmailConfirmation", resourceCulture);
            }
        }
        
        public static string LicenceExpired {
            get {
                return ResourceManager.GetString("LicenceExpired", resourceCulture);
            }
        }
        
        public static string UserBlocked {
            get {
                return ResourceManager.GetString("UserBlocked", resourceCulture);
            }
        }
        
        public static string NeedsConfirmUserChange {
            get {
                return ResourceManager.GetString("NeedsConfirmUserChange", resourceCulture);
            }
        }
        
        public static string NoInternt {
            get {
                return ResourceManager.GetString("NoInternt", resourceCulture);
            }
        }
        
        public static string ErrorDeviceRegister {
            get {
                return ResourceManager.GetString("ErrorDeviceRegister", resourceCulture);
            }
        }
        
        public static string PleaseContactUs {
            get {
                return ResourceManager.GetString("PleaseContactUs", resourceCulture);
            }
        }
        
        public static string UsedOf {
            get {
                return ResourceManager.GetString("UsedOf", resourceCulture);
            }
        }
        
        public static string LogoutQuestion {
            get {
                return ResourceManager.GetString("LogoutQuestion", resourceCulture);
            }
        }
        
        public static string LogoutQuestionChatHistory {
            get {
                return ResourceManager.GetString("LogoutQuestionChatHistory", resourceCulture);
            }
        }
    }
}
